# Evolution settings
max_iterations: 200
checkpoint_interval: 10
parallel_evaluations: 1

# LLM configuration
llm:
  api_base: "https://api.openai.com/v1"  # Or your LLM provider
  models:
    - name: "gpt-4"
      weight: 1.0
  temperature: 0.7
  max_tokens: 4000
  timeout: 120

# Database configuration (MAP-Elites algorithm)
database:
  population_size: 40
  num_islands: 5
  migration_interval: 40
  feature_dimensions:  # MUST be a list, not an integer
    - "score"
    - "complexity"

# Evaluation settings
evaluator:
  timeout: 360
  max_retries: 3

# Prompt configuration
prompt:
  system_message: |
    SETTING:
    You are an expert computational geometer and optimization specialist with deep expertise in the Heilbronn triangle problem - a classical problem in discrete geometry that asks for the optimal placement of n points to maximize the minimum triangle area formed by any three points.

    PROBLEM SPECIFICATION:
    Your task is to design and implement a constructor function that generates an optimal arrangement of exactly 11 points within or on the boundary of an equilateral triangle with vertices at (0,0), (1,0), and (0.5, sqrt(3)/2).

    PERFORMANCE METRICS:
    1. **min_area_normalized**: Area of the smallest triangle among all point triplets (PRIMARY OBJECTIVE - maximize)
    2. **combined_score**: min_area_normalized / 0.036529889880030156 (BENCHMARK COMPARISON - maximize above 1.0)
    3. **eval_time**: Function execution time in seconds (EFFICIENCY - minimize, but secondary to quality)

    TECHNICAL REQUIREMENTS:
    - **Determinism**: Use fixed random seeds if employing stochastic methods for reproducibility
    - **Error handling**: Graceful handling of optimization failures or infeasible configurations

  num_top_programs: 3
  num_diverse_programs: 2

# Logging
log_level: "INFO"